src/config/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shortener.urls')),
]

src/shortener/urls.py
from django.urls import path

from .views import RedirectView
from .views import StatisticsView
from .views import URLShortenerView


app_name = 'url_shortener'

urlpatterns = [
    path('', URLShortenerView.as_view(), name='url_shortener'),
    path('r/<str:short_hash>/', RedirectView.as_view(), name='redirect'),
    path('statistics/', StatisticsView.as_view(), name='statistics'),
]

src/shortener/models.py
from django.db import models


class Link(models.Model):
    """
    Модель, представляющая сокращенную ссылку
    """

    original_url = models.URLField()
    short_hash = models.CharField(max_length=6, unique=True)
    views_counter = models.PositiveIntegerField(default=0)

    def increment_views_counter(self) -> None:
        """
        Увеличивает количество переходов для определенной ссылки
        """
        self.views_counter += 1
        self.save()

src/shortener/forms.py
from django import forms
from django.forms import URLInput


class URLShortenerForm(forms.Form):
    """
    Форма для принятия полной ссылки и последующего сокращения
    """

    # URLField принимает URL от пользователя
    url = forms.URLField(
        label='',
        # Кастомные error messages
        error_messages={'required': 'Введите корректную ссылку'},
        # URLInput widget to render the form field
        widget=forms.URLInput(
            attrs={
                'class': 'form-field',
                # Образец для ввода ссылки
                'placeholder': 'https://example.com/',
            }
        ),
    )

src/shortener/views.py
from django.http import HttpResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.views import View
from django.views.generic import FormView
from django.views.generic import TemplateView

from .forms import URLShortenerForm
from .models import Link
from .utils import create_csv_file
from .utils import create_xlsx_file
from .utils import get_paginated_links
from .utils import get_sorted_links
from .utils import save_url_mapping


class URLShortenerView(FormView):
    """
    URLShortenerView обеспечивает функционал сократителя ссылок
    Обеспечивает рендер формы и принятия данных, внесенных в нее
    """

    template_name = 'shortener/url_shortener.html'
    form_class = URLShortenerForm

    def form_valid(self, form: URLShortenerForm):
        """
        Метод вызывается при валидной передаче данных в форму
        Он сокращает оригинальную ссылку и передает новый хеш ссылки

        :param form: Данные из формы
        :type form: URLShortenerForm
        :return: Рендерит ответ с хешем ссылки
        :rtype: HttpResponse
        """
        url = form.cleaned_data['url']
        short_hash = save_url_mapping(url)
        context = {'short_hash': short_hash}
        return render(self.request, 'shortener/url_shortener.html', context)


class RedirectView(View):
    """
    RedirectView обеспечивает функционал перенаправления пользователя с сокращенной ссыллки на оригинальную.
    """

    def get(self, request, short_hash: str):
        """
        Метод вызывается при запросе GET
        Он увеличивает количество переходов на 1 и перенаправляет на оригинальный url

        :param request: Django request object
        :type request: HttpRequest
        :param short_hash: Хеш оригинальной ссылки
        :type short_hash: str
        :return: Перенаправляет на оригинальную ссылку
        :rtype: HttpResponseRedirect
        """
        mapping = Link.objects.get(short_hash=short_hash)
        mapping.increment_views_counter()
        return redirect(mapping.original_url)


class StatisticsView(TemplateView):
    """
    Выводит статистику по всем сокращенным ссылкам и количествами переходов по ним
    """

    template_name = 'shortener/statistics.html'

    def get(self, request, *args, **kwargs):
        """
        Обрабатывает GET запрос для вывода статистики

        Статистика сортируется по query string параметру sort_by, по-умолчанию стоит 'views_counter'
        Обработанные данные проходят пагинацию и выводятся на страницу

        Если в GET запросе передан параметр download_csv, то статистика выгружается в .csv файле
        Если в GET запросе передан параметр download_xlsx, то статистика выгружается в .xlsx файле

        :param request: входящий request object
        :type request: django.http.HttpRequest
        :param args: дополнительные аргументы
        :type args: list
        :param kwargs: дополнительные ключевые аргументы
        :type kwargs: dict
        :return: ответ на запрос
        :rtype: django.http.HttpResponse
        """
        # Сортирует данные на основе sort_by параметра, по-умолчанию стоит 'views_counter'
        sort_by = request.GET.get('sort_by', 'views_counter')
        links = get_sorted_links(sort_by)

        # Если в GET запросе передан параметр download_csv, то статистика выгружается в .csv файле
        if request.GET.get('download_csv'):
            create_csv_file(links)
            file = open('statistics.csv', 'r')
            response = HttpResponse(file, content_type='text/csv')
            response[
                'Content-Disposition'
            ] = 'attachment; filename="statistics.csv"'
            return response

        # Если в GET запросе передан параметр download_xlsx, то статистика выгружается в .xlsx файле
        elif request.GET.get('download_xlsx'):
            create_xlsx_file(links)
            file = open('statistics.xlsx', 'rb')
            response = HttpResponse(
                file.read(),
                content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            )
            response[
                'Content-Disposition'
            ] = 'attachment; filename="statistics.xlsx"'
            return response

        # Получает количество страниц для вывода на сайте, по-умолчанию стоит значение 1
        page = request.GET.get('page', 1)

        # Пагинирует ссылки
        links = get_paginated_links(links, page_number=page)

        # Обновляет context ссылками, прошедшими пагинацию
        context = self.get_context_data(**kwargs)
        context['links'] = links

        # Отправка ответа

        return self.render_to_response(context)

src/templates/shortener/navbar.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Меню</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Сократитель ссылок</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'url_shortener:url_shortener' %}">Сократитель ссылок</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'url_shortener:statistics' %}">Статистика</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container my-5">
      {% block content %}{% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

src/templates/shortener/statistics.html
{% extends 'shortener/navbar.html'%}
{% load static %}
{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'shortener/css/statistics.css' %}">
  <div class="d-flex justify-content-center my-3">
    {% if links.has_previous %}
      <a class="btn btn-secondary" href="?sort_by={{sort_by}}&page={{ links.previous_page_number }}">&laquo; Предыдущая</a>
    {% endif %}
    <span class="mx-3">Страница {{ links.number }} из {{ links.paginator.num_pages }}</span>
    {% if links.has_next %}
      <a class="btn btn-secondary" href="?sort_by={{sort_by}}&page={{ links.next_page_number }}">Следующая &raquo;</a>
    {% endif %}
    <a href="?sort_by=views_counter" class="btn btn-secondary">Сортировать по возрастанию</a>
    <a href="?sort_by=-views_counter" class="btn btn-secondary">Сортировать по убыванию</a>
    <a href="?download_csv=True" class="btn btn-secondary">Загрузить в CSV</a>
    <a href="?download_xlsx=True" class="btn btn-secondary">Загрузить в Excel</a>
  </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Оригинальная ссылка</th>
          <th>Хеш ссылки</th>
          <th>Количество переходов</th>
        </tr>
      </thead>
      <tbody>
        {% for link in links %}
        <tr>
          <td>{{ link.original_url }}</td>
          <td>{{ link.short_hash }}</td>
          <td>{{ link.views_counter }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="report_downloads">

  </div>
{% endblock %}

src/templates/shortener/url_shortener.html
{% extends 'shortener/navbar.html'%}
{% load static %}
{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'shortener/css/shortener.css' %}">
  <div class="form-container">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="{% if short_hash %}Вернуться назад{% else %}Сократить ссылку{% endif %}">

      {% if short_hash %}
        <p class="short-link"><a href="{{ request.build_absolute_uri }}{% url 'url_shortener:redirect' short_hash %}">{{ request.build_absolute_uri }}{% url 'url_shortener:redirect' short_hash %}</a></p>
      {% endif %}
    </form>
    <div class="form-errors">
      {% for error in form.non_field_errors %}
        <p class="error">{{ error }}</p>
      {% endfor %}
      {% for field in form %}
        {% for error in field.errors %}
          <p class="error">{{ field.label }}: {{ error }}</p>
        {% endfor %}
      {% endfor %}
    </div>
  </div>
{% endblock %}